// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftinrssbzrfkvxmjmxzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0aW5yc3NienJma3Z4bWpteHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTY5NDQsImV4cCI6MjA2NjQ5Mjk0NH0.82_vV2MXmwTCY_Hb-tU3jVSqZQglY0b_L-cXqU_nYM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);